require('./config$');
require('../..//page/login/index');
require('../..//page/home/index');
require('../..//page/cart/cart');
require('../..//page/user/user');
require('../..//page/bill/bill');
require('../..//page/order/order');
require('../..//page/member/member');
require('../..//page/helpCenter/helpCenter');
